### ISSUE TITLE
Sequence per Wallet?

### ISSUE THREAD

**Issue by jaekwon** [tendermint/clearchain#8]
Comparing ClearChain to Basecoin, I see that each Account has many sequences, one per wallet.  Is this to help parallelize transactions across wallets?

I'd like to read more about the use-cases or design considerations for this, so that maybe we incorporate these changes into Basecoin.

**Comment by alessio** [comment]
Closing this as we've ported clearchain to Cosmos SDK. Hence, sequence numbers are no longer handled by the application.
